### ISSUE TITLE
Aggressive on-boarding process

### ISSUE THREAD

**Issue by yuchi** [yuchi/frontend-resources-osgi#1]
Hello everyone!

I’m going to invoke here all the people I personally believe have something to say on the topic. Those officially entitled by a eminent role in the community or by a position in Liferay Inc. itself **are going to be added as commiters** on the repo.

Please feel free to invoke others as you wish.

I therefore invoke
- @natecavanaugh for obvious reasons, but mostly because he’s the one that will have to orchestrate the whole thing
- @rotty3000 for obvious reasons, but mostly for his affiliation and deep knowledge of the OSGi world
- @Ithildir for his involvement in the build process for Liferay and general interest in… things
- @EmilOberg for his presence in the community and Front-end knowledge

BTW I knew beforehand I’d have looked spammy.

**Comment by yuchi** [comment]
Because they have driven the process of creation of both Liferay AMD Loader and Metal.js I think I should also call here
- @zenorocha
- @eduardolundgren

**Comment by yuchi** [comment]
Other people whose voice I care about:
- @GustavCarlson
- @mmariuzzo

**Comment by rotty3000** [comment]
I would include @pkriens, the author of [RFP-171 Web Resources](https://github.com/osgi/design/raw/master/rfps/rfp-0171-Web-Resources.pdf), creator, maintainer of the [OSGi enRoute](http://enroute.osgi.org/) project which has a initial, light OSGi web resource implementation.

**Comment by pkriens** [comment]
You're sure Ray? :-) 

I actually would like to have a conversation about this since Web Resources is one of the nicest things I've implemented in OSGi enRoute

**Comment by yuchi** [comment]
Thank you so much @rotty3000.

@pkriens, honored to have you in the discussion. I’d like to give you a fast track to what we actually talked about, and what we (I) felt was missing by the current state of things.
Because I don’t know how deep is your knowledge of the Liferay specific domain I’ll probably look like an apprentice explaining what meditating is to a zen-master.

---
- Liferay is/has an OSGi container.
- The final product of a Liferay webpage is actually the result of many different actors, mostly portlets and a theme, glued by the Portal itself.
- Every actor on the page could have dependencies on publicly available front-end libraries, driving the resolution and retrieval of those dependencies based on identifiers to be found in a registry (npm, github, github through bower, jsp…) for a version range.
- Every actor could depend on other actor’s resources, or they could share a dependency.
- Actors are going to be shared through the Liferay Marketplace and no development time should be required to compose them.

The state of the portal let’s you do the following:
- In your bundle you use bower to manage your dependencies
- In your code you use AMD (or transpile to it) to ‘use’ the dependent resources
- The Liferay Build Process (through its AMD Loader Config Generator) can correctly bind your named requirements to the provided resources
- Resources are then bundled along-side your dependencies in the final bundle
- In another bundle I can ‘require’ resources exposed by other bundles

That means that if I create a ~~portlet~~ bundle that uses a library (e.g. React) I need to either
- have a bundle which wraps and exposes React or
- embed React itself in my bundle.

If more than a single bundle requires that same library I either have to go with the bundle-way or let those have duplicate resources. Duplicating the library is not always possible because one bundle could provide functionality to be injected in the context (and `instanceof React.Component` must work with obejcts coming from one side or another).

So what’s the issue with having a `React@0.14.0` OSGi bundle?

Let‘s break it down to smaller pain points:
- Where should the bundle be stored? Maven repository? Well…
  - React, Angular, Ember etc. are already ‘bundles’, but they use a different name: packages;
  - they are already stored elsewhere, on GitHub for bower and on the npm-registry (or an Enterprise installation of it) for npm;
- Keeping in mind that the two bundles could be downloaded from the Marketplace and built by different companies, who is the maintainer of the React bundle? The right answer would be Facebook, but that means that there’s another distribution strategy for JavaScript packages? Don’t forget that…
- Front-end guy probably don’t even know what OSGi or Maven or Maven Central is;
- AFAIK version ranges in OSGi and npm/bower/js-flavoured-semver are not compatible. I believe OSGi’s ones are a subset of JS’s ones.

Even if those where superable don‘t forget that code that is written for npm or bower expect a browserify/webpack/SystemJS infrastructure and dependency resolution algorithm.

For Liferay guys here, there’s also that funny problem about dependencies of dependencies. If I really need to, as a Liferay developer, I can run the Liferay Module Config Generator on my code, but I can’t expect Lo-dash to do the same.

---

Please, @pkriens, @rotty3000, everyone tell me if my explanation is not clear or if I’m missing some important piece of the puzzle.

**Comment by yuchi** [comment]
BTW I’m trying to write a [small guide](https://github.com/yuchi/frontend-resources-osgi/blob/master/To_know_for_javaists.md) to bring OSGi gurus on track with the state of things on packaging, distribution and modules on JavaScript and the Web Front-end stuff.

**Comment by natecavanaugh** [comment]
Thanks Pier :)
I would also include @jbalsas, @brunobasto and @mjbradford89 as they have also been working on the front end infrastructure part of OSGi in the portal, and I believe @jbalsas may start working on integration with [WebJars](http://www.webjars.org/) soon.

**Comment by yuchi** [comment]
Thank you @natecavanaugh! I had an eye on WebJars and having it in Liferay would bring us a step closer to the future.

Just for an initial discussion, probably pointed specifically to @jbalsas, I have few pretty sparse points on my radar that WebJars don't automatically solve. I'd be very happy if you shared your vision on these:
- how will we treat CommonJS modules? (those that `module.exports=something`)
- will WebJars blend on the OSGi infrastructure?
- will WebJars be placed in a global context?
  - if **not** how will co-dependency work? (e.g. two libs need to share the same version of React/Angular)
  - if **yes** how will we treat version collisions? I _personally expect_ Liferay to act as a single npm (v3) consumer would, where a dependencies tree as flat as possible is calculated (and maintained!)
- if we're going with WebJars will we really need to use pom.xml to manage npm dependencies? what about the subtle differences between `dependencies` and `peerDependencies`?
- will Metal and others be deployed as WebJars?

**Comment by jbalsas** [comment]
Hey @yuchi!

I'm going to need some time to evaluate all you've put together here, so I just wanted to drop a couple of lines in the meantime.

About **WebJars**, the idea for now is just to have a more sane way of managing our third-party dependencies in build-time and stop being forced to copy paste those in our own repo. Just a little step into the future :wink: 

For now we're packaging everything the same way as before, so the build process grabs what it needs from the jars and places it in the same place. This is the initial [PR](https://github.com/Ithildir/liferay-portal/pull/127). Two cool things here, [easier version upgrades](https://github.com/jbalsas/liferay-portal/commit/74ef68549bee3a4a06fb43e6a520cbe0d78e6332) and (+747 −25,309 changes :joy:)

@migue mentioned that they've actually had some conversations with the WebJars team to add support for OSGi-like jars, so that's another line of work worth exploring...

On a **general note**, I think we want to make sure everyone can use its tool of preference when it comes to building bundles and we want to make those workflows as simple as possible. For interop between bundles, we can already _kinda_ do it using common OSGi features. We even included some sugar on top of `bower.json` so you can already define dependencies with other bundles. 

IMO, it's key to push the WebResources RFP forward and make it a reality.

Promise I'll be back with more stuff whenever I catch up with everything :wink:

**Comment by yuchi** [comment]
@jbalsas that's awesome, great initial insight.

**Comment by eduardolundgren** [comment]
@yuchi Be aware that we are aligned with the proposal, we had a meeting this week about this topic and possibly inspired by this issue. Thank you for the insights.

**Comment by yuchi** [comment]
Thank you Eduardo, would it be possible for you to place minutes here or somewhere?

**Comment by eduardolundgren** [comment]
@yuchi Sure, @jbalsas is looking into it and as soon as he presents we can describe here.

**Comment by yuchi** [comment]
I think the on-boarding process can be closed now. If anyone wants to jump on the wagon is welcome.
