### ISSUE TITLE
Initial points for discussion

### ISSUE THREAD

**Issue by yuchi** [yuchi/frontend-resources-osgi#3]
While waiting the minutes from the meeting happened in Liferay, I’d like to share this internal monologue I had in the last weeks. Recently I shared it with @mmariuzzo and it didn’t sound that stupid, that’s why I’m sharing it.

It’s going to be in the Joyce’s stream of consciousness style.

---

Currently we have AMD support within Liferay. That means that if the Loader’s runtime has the right configuration we can then `require` modules and submodules of a dependent package. **I’m still not bought on _not_ supporting CommonJS**, but let’s skip this.

The configuration that is going to be passed to the runtime for each module loaded will be (must be) in the abstract form `Map<Name, Id>` so that `require` is actually double pass: resolve from `name` to `id` and then load the module with that `id`. For `underscore` we might map to `org.webjars.npm.underscore`, because **what we’ll load must be somewhere in a JAR (bundle?)**. Wait, what will the actual URI of that resource be? (Combo loading is just an implementation detail)
An inital idea could be

```
http://localhost/osgi-resource/org.webjars.npm.underscore
```

but…
- Given that the _package.json_ of underscore has `{ main: "./underscore.js" }` should the resolved id be `org.webjars.npm.underscore/underscore.js`?
- Wait, we have `npm` in it that means that **if someone exposes it from Bower we will have duplicates**! But they will actually be different packages (different tarballs)! There’s no way to ‘merge’ them as they were coming from the same place.
- What if someone else wants to load a different version? **We need the version in it**.

So let’s move to

```
http://localhost/osgi-resource/org.webjars.npm.underscore/1.8.3/underscore.js
```

Awesome! But we have not solved the problem about npm/bower. I believe there’s no way around it if not completely ditching one of them. (Hey, what about other registries? let’s skip future-proofing-ness by now)

But how did we know that the version my consumer actually wants is `1.8.3`? Probably in my _package.json_ I have `"underscore": "^1.8.0"` and when I built my bundle and ran the config generator the version I installed through npm was `1.8.3` and the config generator catches that one.
This doesn’t look good, it means we’re shrink-wrapping my dependencies at build time! That means the dependencies sharing will work exclusively for different consumers that **were built with the same dependencies versions! Not good!**
We‘re diverging from the semantics of dependencies graph flattening of npm here. (By the way, Node.js has nothing to say about this, all lies in how npm v3 lays dependencies down during the installation).

---

<p align="center">(to be continued)</p>

**Comment by yuchi** [comment]
Ok, to solve that problem the configuration that I can create at build time is not in the form `Map<Name, Id>` but rather in the form `Map<Name, RangeId>`.
Instead of mapping `underscore` to `npm:underscore@1.8.3/underscore.js` we need to map it to `npm:underscore@^1.8.0`. I’m not appending `/underscore.js` because the package.json could change in another version.
By the way we’re copying `jspm` semantics here, which is good! There’s prior-art to base our work on.
Also I’d like to note that we’re unaware of browserify’s browser specific aliases, let’s keep this for a later review.

So given the following _my-consumer.js_

``` js
import _ from 'underscore';
import chunk from 'lodash/array/chunk';
import secret from '@yuchi/passwords/github';
```

and _package.json_

``` json
// package.json
{
  "name": "it.smc.myproject",
  "dependencies": {
    "underscore": "^1.8.0",
    "lodash": "3.x",
    "@yuchi/passwords": "*"
  }
}
```

the _configuration.json_ we can ~~send to the Loader~~ deploy to the server is

``` json
{
  "path": "it.smc.myproject@0.1.3/my-consumer.js",
  "requires": {
    "underscore": [
      "npm", "underscore", "^1.8.0", null],
    "lodash/array/chunk": [
      "npm", "lodash", "3.x", "/array/chunk" ],
    "@yuchi/passwords/github": [
      "npm", "@yuchi/passwords", "*", "/github" ]
  }
}
```

where the form of a _require resolution_ is `[ registry, name, range, submodule ]`.

Awesome, what we are storing, building and deploying is perfectly consistent with the semantics of npm. If we could ditch any cacheing optimizations we can then use that configuration **to dynamically load the required modules from the server** from the **packages with the highest version that matches the specified range**.
That means that **in the server lies a flat registry of packages** installed, where the final, absolute name is composed of `registry:package-name:version`. (Which is almost exactly what jspm does! [see here under "Registry"](http://jspm.io/))

If we review the build process that leads to the configuration above from start to finish we see at least two pain points:
- will we generate this configuration for every file that matches some pattern? do we define the entry points of our ~~module~~ package? Thinking about it **we need to have the configuration laid down for every file because they could be eventually required by someone else** (also in a future deployment!)
- what about dependencies? we need to parse those too because **every loadable resource needs its own configuration**, and we cannot store the configuration of dependencies with the configuration of the main modules because dependencies could change with a deploy of a newer version later in time.

That means that **what can be downloaded through the WebJars registry is simply not ready**, we need to parse it.
We are in front of a dilemma, we either
- force webjars/packages to pass through the parsing phase, or
- build the configuration at deploy time or on demand.

In the former we are not supporting _vanilla WebJars_ or _vanilla npm packages_, in the latter we are giving the server (Liferay code or a standalone standard library) a lot of power over packages. **We are going to have a static source code analyzer for JavaScript written in Java** for our server to do that. Not. Good. At. All. We just got rid of _SassToCssBuilder_ and we get something even more invasive and non-future-proof.

Let’s make it clear why having a static analyzer in the server is a Bad Idea™:
- it is going to be expensive, way more than the SASS builder, but here I’m just spreading FUD;
- we lock our JavaScript output to the version and subset _we_ understand, for example EcmaScript 2015, because that’s what our analyzer understands;
- even implementing it is going to be a crazy thing to do (not for its difficulty but for its complexity) when we have awesome, supported, battle-tested-by-package-providers (this one is huge IMHO) solutions out there.

---

<p align="center">(to be continued, again)</p>

**Comment by yuchi** [comment]
Let‘s say we somehow solve that issue about who, when and how a package is parsed. I’m sure we can find other interesting areas for discussion if we go on analyzing the scenario.

In fact, once our parsing system is up and running, we still don’t know how to deploy packages to our server. In Liferay we could
- have a nice `data/packages` directory which follows jspm structure or something along the lines;
- deploy things as JARs/bundles inside the OSGi modules directory;
- keep packages inside their consumer.

Let’s analyze PROs and CONs.

Keeping dependencies inside the consumer means we exactly know who placed what in the registry, but we could have a hard time keeping a deterministic approach when we have colliding packages. Also it would be extremely difficult to manage the registry, because it is spread in different places.

Deploying everything as JARs in the OSGi container is interesting because we have already everything in place, but it could have issues with the semantic versioning of packages, which is `major.minor.build-stuff` instead of `major.minor.build`. Also we could be tempted to use OSGi semantic version ranges to map dependencies, which doesn’t necessarily map to npm/jspm/bower ranges. I still have to check this.

Having a directory for packages seems the best idea to me, because it let us be freely organize things and, more importantly, keep stuff in the format we want. For npm packages the ‘official’ tarball looks promising to solve ownership and security issues.

Ah! Interesting topic. Given that a package version can be provided by two different consumers, which one wins? And how can I be sure that those consumer bundle is not _poisoned_? **If what we have is a set of (extracted or still compressed) packages inside the consumer bundle, what tells us we can trust them?** Simply nothing.

We could go to the npm registry and ask for hash of the distributed tarball and test the validity. If you try to lookup the registry (for example with https://registry.npmjs.org/underscore) you get a huge JSON with `.versions[version].dist.tarball` which is the location of the tarball and `.versions[version].dist.shasum` which is the hash we were looking for. Awesome.

**If the server needs to check the validity of tarballs we are forcing the server to connect to the Internet.** This is not the case in corporate scenarios. What about `check.npm.resources.identity = true/false`?
But if they have any issue with this they can go with _npm On-Site_ and mirror the public registry with their own. This is not a bad idea at all. They already have a private registry for Maven probably, so they will not be unaware of this kind of stuff.

Anyway a good thing we enable by separating the dependencies and the consumer is **the ability to update dependencies without a new deploy/build of consumers**. This is because dependencies are usually expressed as ranges, and we can update those accordingly to our needs and QA ability without consumers having to worry.

We can even have something similar to gogo to manage packages installed on the server and having this console download new packages from available registries.

---

<p align="center"><em>fin</em><p>

**Comment by yuchi** [comment]
Points not discussed above:
- bootstrapping and independent update process for the Loader (having it distributed through npm/bower and then as WebJar and included as a simple resource in the Portal? dunno…);
- transpilation of modules—when, where and how;
- prior-art on architectures with the same complexity (I’m thinking of Atom).

Points not discussed but cited above:
- support for synchronous module definition;
- collision of packages on different registries (npm/bower/webjars/…)
- being future-proof on registries;
- how to actually build the configuration for packages.

**Comment by yuchi** [comment]
@emiloberg @GustavCarlson @mmariuzzo Anything to add?

@jbalsas @natecavanaugh @eduardolundgren @brunobasto Could you please express how different is this story from yours?

@pkriens @rotty3000 I’m very interested in what you see from the OSGi side of things. How distant are we from this story, implementation-wise?

**Comment by yuchi** [comment]
Also cited but not discussed:
- where to place the cache and how aggressive can we be;
- impact on HTTP1/2, cache and Combo Loading;
- support for [browserify `"browser"` extension to the package descriptor](https://github.com/defunctzombie/node-browser-resolve);

Not cited but worth a note:
- support for browserify and webpack transformations (see React’s [usage of `envify`](https://github.com/facebook/react/blob/96549a1f4822b8038b0f8c85cc2216b855460846/packages/react/package.json#L25))

**Comment by natecavanaugh** [comment]
@yuchi Sorry for the late reply, but I need to filter my github notifications a bit better :) I'll read it tonight and try to respond tomorrow.
Thanks Pier :)

**Comment by yuchi** [comment]
Thanks @natecavanaugh, the most important thing is IMHO to define a dev story to work on.

**Comment by yuchi** [comment]
Closing for obsolescence
